application_FFR/admin_base/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'admin_base'

urlpatterns = [

    path('index/', views.index, name='index'),

]

application_FFR/application_FFR/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView
from registration.views import CustomLoginView
from django.contrib.auth import views as auth_views
from registration.templates.registration import *

admin.site.site_header = 'Gestion des comptes'
admin.site.site_title = 'Gestion des comptes'
admin.site.index_title = ''


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', CustomLoginView.as_view(),name='login'),
    path('admin_base/', include('admin_base.urls')),
    path('admin_compte/', include('admin_compte.urls')),
    path('admin_liste/', include('admin_liste.urls')),
    path('admin_stock/', include('admin_stock.urls')),
    path('registration/', include('registration.urls')),
    path('user_liste/', include('user_liste.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

application_FFR/logistique_service_medical/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'logistique_service_medical'

urlpatterns = [

    path('index/', views.index, name='index'),
    path('user_list/', views.user_list, name='user_list'),
    path('add_user/', views.AddUserView.as_view(), name='add_user'),
    path('delete_user/', views.delete_user, name='delete_user'),
    path('consommables/', views.stock_consommables, name='stock_consommables'),
    path('select_stock/', views.select_stock, name='select_stock'),
    path('display_produits/', views.display_produits, name='display_produits'),
    path('produit_list/', views.produit_list, name='produit_list'),
    path('add_produit/', views.add_produit, name='add_produit'),
    path('delete_produit/', views.delete_produit, name='delete_produit'),  # Nouvelle vue pour supprimer un produit
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),  # Utilisation de votre vue d'inscription personnalisée
    path('favoris/', views.favoris, name='favoris'),
    path('update_quantity/<int:id_produit>/', views.update_quantity, name='update_quantity'),
    path('depart/', views.depart, name='depart'),
    path('remplir_liste_depart/<int:id_liste_depart>/<int:id_produit>/', views.remplir_liste_depart, name='remplir_liste_depart'),
    path('create_liste_utilisateur/<int:id_liste_depart>/', views.create_liste_utilisateur, name='create_liste_utilisateur'),
    path('depart_retour/', views.depart_retour, name='depart_retour'),
    path('retour/', views.retour, name='retour'),
    path('verifier_liste_retour/<int:id_liste_utilisateur>/<int:id_produit>/', views.verifier_liste_retour, name='verifier_liste_retour'),
    path('valider_liste_retour/<int:id_liste_utilisateur>/', views.valider_liste_retour, name='valider_liste_retour'),
    path('liste_utilisateur_creee/', views.liste_utilisateur_creee, name='liste_utilisateur_creee'),
    path('mise_a_jour_stock/', views.mise_a_jour_stock, name='mise_a_jour_stock'),
    path('index_utilisateur/', views.index_utilisateur, name='index_utilisateur'),
    path('ma_liste/', views.ma_liste, name='ma_liste'),
    path('remplir_liste_retour/<int:id_liste_utilisateur>/<int:id_produit>/', views.remplir_liste_retour, name='remplir_liste_retour'),
    path('recherche_archive/', views.recherche_archive, name='recherche_archive'),
    path('display_archive/', views.display_archive, name='display_archive'),
]

application_FFR/logistique_service_medical/views.py
from django.contrib.auth.decorators import user_passes_test
from .permissions import is_admin, is_standard_user
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from datetime import datetime
from django.template import loader
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from .forms import *
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
import logging
from django.contrib.auth.models import User
from .business.components.gestion_stock import Gestion_stock
from .business.components.gestion_equipe import Gestion_equipe
from .business.components.gestion_deplacement import Gestion_deplacement
from .business.components.gestion_liste_depart import Gestion_liste_depart
from .business.components.gestion_liste_utilisateur import Gestion_liste_utilisateur
logger = logging.getLogger("django")




class CustomLoginView(LoginView):
    def get_success_url(self):
        user = self.request.user
        if user.is_superuser:
            return 'logistique_service_medical/index'  # Rediriger l'administrateur vers la page d'administration
        else:
            return 'logistique_service_medical/index_utilisateur'  # Rediriger l'utilisateur standard vers une autre page après la connexion


# Gestion utilisateur
class RegisterView(CreateView):
    form_class = RegisterForm
    success_url = reverse_lazy('login')  # Redirection vers la page de connexion après inscription
    template_name = 'registration/register.html'  #


@user_passes_test(is_admin)
def user_list(request):
    users = User.objects.all()
    add_user_form = RegisterForm()
    delete_user_form = DeleteUserForm()
    return render(request, 'logistique_service_medical/user_list.html',
                  {'users': users, 'add_user_form': add_user_form, 'delete_user_form': delete_user_form})


class AddUserView(SuccessMessageMixin, CreateView):
    template_name = 'logistique_service_medical/user_list.html'
    form_class = RegisterForm
    success_url = reverse_lazy('logistique_service_medical:user_list')
    success_message = "Utilisateur ajouté avec succès."


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['add_user_form'] = self.get_form()  # Ajouter le formulaire au contexte
        return context

@user_passes_test(is_admin)
def delete_user(request):
    if request.method == 'POST':
        delete_user_form = DeleteUserForm(request.POST)
        if delete_user_form.is_valid():
            user_id = delete_user_form.cleaned_data['user_id']
            user_to_delete = User.objects.filter(id=user_id).first()
            if user_to_delete:
                user_to_delete.delete()
    return redirect('logistique_service_medical:user_list')

# Page acceuil
@user_passes_test(is_admin)
def index(request):
    logger.debug("entrée dans la view 'Index'")
    template = loader.get_template('logistique_service_medical/index.html')
    context={}
    logger.warning('le contexte pour la view est vide')

    logger.info(f"Définition des villes favorites pour l'utilisateur")
    liste_villes_favorites = ['Paris', 'Lyon', 'Strasbourg']
    request.session['favoris'] = liste_villes_favorites

    logger.debug("sortie dans la view 'Index', rendu du tempate...")

    return HttpResponse(template.render(context, request))

# Gestion stock

@user_passes_test(is_admin)
def stock_consommables(request):
    gestion_stock = Gestion_stock()
    consommables = gestion_stock.get_1()
    context = {'consommables': consommables}
    return render(request, 'logistique_service_medical/stock_consommables.html', context)

@user_passes_test(is_admin)
def select_stock(request):
    gestion_stock = Gestion_stock()
    liste_stocks = gestion_stock.get_all()  # Utilise la méthode get_all de Gestion_stock
    context = {
        'liste_stocks': liste_stocks,
    }
    return render(request, 'logistique_service_medical/select_stock.html', context)


@user_passes_test(is_admin)
def display_produits(request):
    gestion_stock = Gestion_stock()
    liste_stocks = gestion_stock.get_all()
    produitsStock = None
    selected_stock_id = ''
    selected_stock_nom = ''

    if request.method == 'POST':
        id_stock = request.POST.get('id_stock')
        if id_stock:
            gestion_stock.stock.id = id_stock
            produitsStock = gestion_stock.get_1()
            selected_stock_id = id_stock
            selected_stock_nom = produitsStock[0]['nom_stock']


    form = ProductQuantityForm()
    context = {
        'produitsStock': produitsStock,
        'liste_stocks': liste_stocks,
        'selected_stock_id': selected_stock_id,
        'selected_stock_nom': selected_stock_nom,
        'form': form,
    }
    return render(request, 'logistique_service_medical/display_produits.html', context)


@user_passes_test(is_admin)
def update_quantity(request, id_produit):
    gestion_stock = Gestion_stock()
    if request.method == 'POST':
        if id_produit:
            new_quantity_key = f'quantity_{id_produit}'
            new_quantity = request.POST.get(new_quantity_key)
            if new_quantity is not None:
                try:
                    gestion_stock.produit.id = id_produit
                    gestion_stock.produit.quantite_en_stock = int(new_quantity)
                    gestion_stock.update_quantity()  # Utilise la méthode update_quantity de Gestion_stock
                    response_message = 'Quantité mise à jour avec succès'
                    return HttpResponse(response_message, status=200)
                except Exception as e:
                    return HttpResponse('Erreur lors de la mise à jour de la quantité', status=400)
            else:
                return HttpResponse('Aucune quantité spécifiée dans la requête', status=400)
        else:
            return HttpResponse('Aucun ID d\'association de stock-produit spécifié dans la requête', status=400)
    return HttpResponse('Méthode de requête invalide', status=405)


@user_passes_test(is_admin)
def produit_list(request):
    gestion_stock=Gestion_stock()
    produits = gestion_stock.get_all_produit()
    add_produit_form = ProduitForm()
    delete_produit_form = DeleteProduitForm()

    # Récupérer le message de succès de la session s'il existe
    success_message = None
    if 'success_message' in request.session:
        success_message = request.session['success_message']
        del request.session['success_message']  # Supprimer le message de la session

    return render(request, 'logistique_service_medical/produit_list.html',
                  {'produits': produits, 'add_produit_form': add_produit_form,
                   'delete_produit_form': delete_produit_form, 'success_message': success_message})


@user_passes_test(is_admin)
def add_produit(request):
    gestion_stock= Gestion_stock()
    save_error = False
    is_create = True
    add_produit_form = ProduitForm()

    if request.method == 'POST':
        is_create = False
        add_produit_form = ProduitForm(request.POST)

        if add_produit_form.is_valid():
            nom_produit = add_produit_form.cleaned_data["nom_produit"]
            quantite = add_produit_form.cleaned_data["quantite"]
            id_stock = add_produit_form.cleaned_data["id_stock"]

            try:
                gestion_stock.produit.nom = nom_produit
                gestion_stock.produit.quantite_en_stock = quantite
                gestion_stock.stock.id = id_stock

                # Afficher les valeurs récupérées dans la console
                print("Nom du produit:", nom_produit)
                print("Quantité:", quantite)
                print("ID du stock:", id_stock)

                gestion_stock.add_produit_stock()
                add_produit_form = ProduitForm()

                # Stocker le message de succès dans la session
                messages.success(request, 'Le produit a été ajouté avec succès.')

                # Rediriger vers la liste des produits
                return redirect('logistique_service_medical:produit_list')

            except Exception as e:
                print(e)
                save_error = True

    # Si l'ajout du produit a échoué, ne pas stocker de message de succès dans la session
    if save_error:
        messages.error(request, 'Erreur lors de l\'ajout du produit.')

    return render(request, 'logistique_service_medical/produit_list.html',
                  {'add_produit_form': add_produit_form, 'save_error': save_error, 'is_create': is_create})

@user_passes_test(is_admin)
def delete_produit(request):
    gestion_stock=Gestion_stock()
    if request.method == 'POST':
        delete_produit_form = DeleteProduitForm(request.POST)
        if delete_produit_form.is_valid():
            id_produit = delete_produit_form.cleaned_data['id_produit']
            try:
                gestion_stock.produit.id = id_produit
                gestion_stock.delete_produit_stock()  # Utilise la méthode delete_produit_stock de Gestion_stock
                messages.success(request, 'Le produit a été supprimé avec succès.')
            except Exception as e:
                messages.error(request, 'Erreur lors de la suppression du produit.')
    return redirect('logistique_service_medical:produit_list')

@user_passes_test(is_admin)
def favoris(request):
    liste_villes_favorites = ['Paris', 'Lyon', 'Strasbourg']
    request.session['favoris'] = liste_villes_favorites
    context = {'favoris': liste_villes_favorites}
    return render(request, 'logistique_service_medical/favoris.html', context)


#Gestion Liste

@user_passes_test(is_admin)
def depart_retour(request):

    template = loader.get_template('logistique_service_medical/depart_retour.html')
    context = {}

application_FFR/logistique_service_medical/templates/logistique_service_medical/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Application logistique service medical FFR</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v6.1.1/js/all.js"></script>
    <script src="https://unpkg.com/htmx.org@^1.7.0/dist/htmx.min.js"></script>
</head>
<body>
<nav class="navbar is-primary is-mobile" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <!-- Titre Accueil avec les mêmes styles que les autres éléments de la navbar -->
        <a class="navbar-item is-size-6 has-text-light" href="{% url 'logistique_service_medical:index' %}">
            Accueil
        </a>
        <!-- Burger avec dropdown -->
        <div class="navbar-burger has-text-light" aria-label="menu" aria-expanded="false" data-target="navbarDropdown">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div>
    <!-- Menu avec dropdown -->
    <div id="navbarMenu" class="navbar-menu">
        <div class="navbar-start">
            <a class="navbar-item has-text-light" href="{% url 'logistique_service_medical:user_list' %}">Comptes</a>
            <a class="navbar-item has-text-light" href="{% url 'logistique_service_medical:display_produits' %}">Stocks</a>
            <a class="navbar-item has-text-light" href="{% url 'logistique_service_medical:depart_retour' %}">Listes</a>
        </div>
    </div>
 <div id="navbarDropdown" class="navbar-menu">
        <div class="navbar-end">
            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link has-text-light">
                    {{ user.first_name }}
                </a>
                <div class="navbar-dropdown is-right">
                    <a class="navbar-item" href="#">About</a>
                    <a class="navbar-item" href="#">Contact</a>
                    <hr class="navbar-divider">
                    <a class="navbar-item" href="{% url 'logistique_service_medical:logout' %}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Se déconnecter</a>
                    <form id="logout-form" action="{% url 'logistique_service_medical:logout' %}" method="post" style="display: none;">
                        {% csrf_token %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</nav>

<div id="content">
    {% block content %}{% endblock content %}
</div>
</body>
</html>
<script>
document.addEventListener('DOMContentLoaded', () => {
  // Get all "navbar-burger" elements
  const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

  // Add a click event on each of them
  $navbarBurgers.forEach( el => {
    el.addEventListener('click', () => {
      // Get the target from the "data-target" attribute
      const target = el.dataset.target;
      const $target = document.getElementById(target);

      // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
      el.classList.toggle('is-active');
      $target.classList.toggle('is-active');
    });
  });
});
</script>

application_FFR/logistique_service_medical/templates/logistique_service_medical/depart.html
{% extends 'logistique_service_medical/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<section class="section has-background-light is-mobile">
<div class="box">
<h1 class="subtitle is-3 has-text-link has-text-centered mb-5 is-flex is-align-items-center is-justify-content-center">
    <span class="icon is-large has-text-warning">
        <i class="fas fa-plane-departure"></i>
    </span>
    <span class="ml-3">Preparer un depart</span>
</h1>
</div>
<div class="box">
<h2 class="subtitle is-4 has-text-link mb-6">Construire un deplacement</h2>
<form action="{% url 'logistique_service_medical:depart' %}" method="post" class="mb-5">
{% csrf_token %}
    <div class="container">
    {% crispy equipe_form %}
    <button class="button is-primary has-text-light" type="submit">Valider le deplacement</button>
    </div>
</form>
</div>

{% if produits_stock %}
<div class="box">
<h2 class="subtitle is-4 has-text-link mb-6">Construire la liste depart</h2>
    <h2 class="subtitle is-5 has-text-centered has-text-link mb-6">{{ selected_stock_nom }}</h2>
    <div class="table-container">
        <table class="table is-striped is-fullwidth">
            <thead>
                <tr>
                    <th>Produit</th>
                    <th>Stock</th>
                    <th>Depart</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for produit in produits_stock %}
                    <tr>
                        <td>{{ produit.nom_produit }}</td>
                        <td>{{ produit.quantite_stock }}</td>
                        <td>
                                <form hx-post="{% url 'logistique_service_medical:remplir_liste_depart' id_liste_depart=id_liste_depart id_produit=produit.id_produit %}" hx-target="#message_{{ produit.id_produit }}" hx-swap="outerHTML">
                                {% csrf_token %}
                                <div class="field">
                                    <div class="control">
                                        <input type="number" id="quantity_{{ produit.id_produit }}" name="quantity_{{ produit.id_produit }}"
                                            value="{{ produit.quantite_depart }}" class="input is-small" min="0" max="{{ produit.quantite_stock }}">
                                    </div>
                                </div>
                                </td>
                            <td>
                                <div class="field is-grouped">
                                    <div class="control">
                                        <button class="button is-primary is-focused is-small has-text-light" name="quantity_updated" type="submit">
                                                <span class="icon is-small">
                                                    <i class="fas fa-check"></i>
                                                </span></button>                                    </div>
                                </div>
                                </form>
                            </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
   </div>
{% endif %}
<div id="successNotification" class="notification is-small is-link" style= "display: none; position: fixed; bottom: 0px; right: 0px ;">
  Quantité mise à jour.
</div>
{% if utilisateur_choice_form %}

<div class="box">
    <h2 class="subtitle is-4 has-text-link mb-6">Attribuer la liste à un utilisateur</h2>
    <form action="{% url 'logistique_service_medical:create_liste_utilisateur' id_liste_depart=id_liste_depart %}" method="post">
        {% csrf_token %}
        <div class="container">
        {% crispy utilisateur_choice_form %}
        <button class="button is-focused is-primary has-text-light" type="submit">Valider la liste utilisateur (mise à jour du stock)</button>
        </div>
    </form>
<div id="message-container"></div>
</div>

{% endif %}

</section>

<script>
document.addEventListener("DOMContentLoaded", () => {
    // Get all forms with the 'hx-post' attribute
    let forms = document.querySelectorAll('[hx-post]');

    // Loop through each form and add submit event listener
    forms.forEach((form) => {
        form.addEventListener('submit', async (event) => {
            event.preventDefault();

            // Prepare the form data
            let formData = new FormData(form);

            // Send the form data asynchronously
            let response = await fetch(form.getAttribute('hx-post'), {
                method: 'POST',
                body: formData
            });

            // Parse the response as plain text
            let responseText = await response.text();

            // Check if the response was successful
            if (response.ok) {
                // Show success notification
                document.getElementById('successNotification').style.display = 'block';

                // Hide success notification after 3 seconds
                setTimeout(() => {
                    document.getElementById('successNotification').style.display = 'none';
                }, 2000);
            } else {
                // Display the error message
                form.querySelector('#message').innerHTML = responseText;
            }
        });
    });
});
</script>

{% endblock %}

application_FFR/logistique_service_medical/templates/logistique_service_medical/depart_retour.html
{% extends 'logistique_service_medical/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<section class="section">
    <div class="container">
        <h1 class="subtitle is-3 has-text-link has-text-centered mb-5 is-flex is-align-items-center is-justify-content-center">
                    <span class="icon has-text-info">
                        <i class="fas fa-clipboard-list"></i>
                    </span><span class="ml-3">Gestion des listes</span></h1>
        <hr>
    <div class="columns is-centered">
            <div class="column is-half has-text-centered">
                <a href="{% url 'logistique_service_medical:depart' %}" class="button is-outlined is-link is-large is-fullwidth mb-5">
                    <span class="icon has-text-warning">
                    <i class="fas fa-plane-departure"></i>
                    </span>
                    <span>Depart</span>
                </a>
                <a href="{% url 'logistique_service_medical:retour' %}" class="button is-outlined is-link is-large is-fullwidth mb-5">
                    <span class="icon has-text-primary">
                        <i class="fas fa-plane-arrival"></i>
                    </span>
                    <span>Retour</span>
                </a>
                </a>
                <a href="{% url 'logistique_service_medical:recherche_archive' %}" class="button is-outlined is-link is-large is-fullwidth mb-5">
                    <span class="icon has-text-info">
                        <i class="fas fa-archive"></i>
                    </span>
                    <span>Archives</span>
                </a>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

application_FFR/logistique_service_medical/templates/logistique_service_medical/index.html
{% extends 'logistique_service_medical/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<section class="section">
    <div class="container">
        <h1 class="title has-text-centered is-1 has-text-link">Logimed</h1>
        <hr>
        <div class="columns is-centered">
            <div class="column is-half has-text-centered">
                <a href="{% url 'logistique_service_medical:user_list' %}" class="button has-text-link is-focused is-large is-fullwidth mb-1">
                    <span class="icon has-text-warning">
                    <i class="fas fa-users"></i>
                    </span>
                    <span>Gestion Comptes</span>
                </a>

            </div>
        </div>
        <div class="columns is-centered">
            <div class="column is-half has-text-centered">
                <button class="button has-text-link is-focused is-large is-fullwidth mb-1" data-url="{% url 'logistique_service_medical:display_produits' %}" onclick="window.location.href = this.getAttribute('data-url')">
                    <span class="icon has-text-primary">
                        <i class="fas fa-box"></i>
                    </span>
                    <span>Gestion Stocks</span>
                </button>
            </div>
        </div>
        <div class="columns is-centered">
            <div class="column is-half has-text-centered">
                <a href="{% url 'logistique_service_medical:depart_retour' %}" class="button has-text-link is-focused is-large is-fullwidth mb-1">
                    <span class="icon has-text-info">
                        <i class="fas fa-clipboard-list"></i>
                    </span>
                    <span>Gestion Listes</span>
                </a>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

application_FFR/logistique_service_medical/templates/logistique_service_medical/retour.html
{% extends 'logistique_service_medical/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<section class="section has-background-light is-mobile">
<div class="box">
<h1 class="subtitle is-3 has-text-link has-text-centered mb-5 is-flex is-align-items-center is-justify-content-center"><span class="icon has-text-primary">
                        <i class="fas fa-plane-arrival"></i>
                    </span><span class="ml-4">Verifier un retour</span></h1>
</div>
<div class="box">
<h2 class="subtitle is-4 has-text-link mb-6">Recuperer la liste utilisateur en cours</h2>
<form action="{% url 'logistique_service_medical:retour' %}" method="post" class="mb-5">
{% csrf_token %}
    <div class="container">
    {% crispy liste_utilisateur_form %}
    <button class="button is-primary has-text-light" type="submit">Choisir</button>
    </div>
</form>
</div>
{% if produits_liste_utilisateur %}
<div class="box">
<h2 class="subtitle is-4 has-text-link mb-6">Verifier la liste utilisateur</h2>
    <h2 class="subtitle is-4 has-text-centered has-text-link mb-6">{{ selected_stock_nom }}</h2>
    <div class="table-container">
        <table class="table is-striped is-fullwidth">
            <thead>
                <tr>
                    <th>Produit</th>
                    <th>Depart</th>
                    <th>Retour</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for produit in produits_liste_utilisateur %}
                    <tr>
                        <td>{{ produit.nom_produit }}</td>
                        <td>{{ produit.quantite_depart }}</td>
                        <td>
                                <form hx-post="{% url 'logistique_service_medical:verifier_liste_retour' id_liste_utilisateur=id_liste_utilisateur id_produit=produit.id_produit %}" hx-target="#message_{{ produit.id_produit }}" hx-swap="outerHTML">
                                {% csrf_token %}
                                <div class="field">
                                    <div class="control">
                                        <input type="number" id="quantity_{{ produit.id_produit }}" name="quantity_{{ produit.id_produit }}"
                                            value="{{ produit.quantite_retour }}" class="input is-small" min="0" max="{{ produit.quantite_depart }}">
                                    </div>
                                </div>
                                </td>
                            <td>
                                <div class="field is-grouped">
                                    <div class="control">
                                                <button class="button is-primary is-focused is-small has-text-light" name="quantity_updated" type="submit">
                                                <span class="icon is-small">
                                                    <i class="fas fa-check"></i>
                                                </span></button>                                    </div>
                                </div>
                                </form>
                            </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

<div id="successNotification" class="notification is-small is-link" style= "display: none; position: fixed; bottom: 0px; right: 0px ;">
  Quantité mise à jour.
</div>


    <form action="{% url 'logistique_service_medical:valider_liste_retour' id_liste_utilisateur=id_liste_utilisateur %}" method="post">
        {% csrf_token %}
        <div class="container">
        <button class="button is-primary has-text-light" type="submit">Valider la liste utilisateur (mise à jour du stock)</button>
        </div>
    </form>
{% endif %}
</div>
</div>
</section>


<script>
document.addEventListener("DOMContentLoaded", () => {
    // Get all forms with the 'hx-post' attribute
    let forms = document.querySelectorAll('[hx-post]');

    // Loop through each form and add submit event listener
    forms.forEach((form) => {
        form.addEventListener('submit', async (event) => {
            event.preventDefault();

            // Prepare the form data
            let formData = new FormData(form);

            // Send the form data asynchronously
            let response = await fetch(form.getAttribute('hx-post'), {
                method: 'POST',
                body: formData
            });

            // Parse the response as plain text
            let responseText = await response.text();

            // Check if the response was successful
            if (response.ok) {
                // Show success notification
                document.getElementById('successNotification').style.display = 'block';

                // Hide success notification after 3 seconds
                setTimeout(() => {
                    document.getElementById('successNotification').style.display = 'none';
                }, 2000);
            } else {
                // Display the error message
                form.querySelector('#message').innerHTML = responseText;
            }
        });
    });
});
</script>


{% endblock %}