application_FFR/admin_base/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'admin_base'

urlpatterns = [

    path('index/', views.index, name='index'),

]

application_FFR/application_FFR/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView
from registration.views import CustomLoginView
from django.contrib.auth import views as auth_views
from registration.templates.registration import *

admin.site.site_header = 'Gestion des comptes'
admin.site.site_title = 'Gestion des comptes'
admin.site.index_title = ''


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', CustomLoginView.as_view(),name='login'),
    path('admin_base/', include('admin_base.urls')),
    path('admin_compte/', include('admin_compte.urls')),
    path('admin_liste/', include('admin_liste.urls')),
    path('admin_stock/', include('admin_stock.urls')),
    path('registration/', include('registration.urls')),
    path('user_liste/', include('user_liste.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

application_FFR/registration/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views
from . import views

app_name = 'registration'

urlpatterns = [

    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),  # Utilisation de votre vue d'inscription personnalisée
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

application_FFR/user_liste/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'user_liste'

urlpatterns = [

    path('index_utilisateur/', views.index_utilisateur, name='index_utilisateur'),
    path('ma_liste/', views.ma_liste, name='ma_liste'),
    path('remplir_liste_retour/<int:id_liste_utilisateur>/<int:id_produit>/', views.remplir_liste_retour, name='remplir_liste_retour'),

]

application_FFR/user_liste/models.py
from django.db import models

# Create your models here.

application_FFR/user_liste/forms.py
from django.forms.models import ModelChoiceField
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Submit
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .business.components.gestion_stock import Gestion_stock
from .business.components.gestion_equipe import Gestion_equipe
from .business.components.gestion_deplacement import Gestion_deplacement

application_FFR/user_liste/views.py
from django.contrib.auth.decorators import user_passes_test
from registration.permissions import is_admin, is_standard_user
from django.shortcuts import render,redirect
from django.http import HttpResponse, JsonResponse
from django.template import loader
import logging
from admin_liste.business.components.gestion_liste_utilisateur import Gestion_liste_utilisateur
logger = logging.getLogger("django")

#Partie Utilisateur
@user_passes_test(is_standard_user)
def index_utilisateur(request):
    template = loader.get_template('index_utilisateur.html')
    context = {}
    return HttpResponse(template.render(context, request))

@user_passes_test(is_standard_user)
def ma_liste(request):

    gestion_liste_utilisateur = Gestion_liste_utilisateur()
    produits_liste_utilisateur = []
    id_liste_utilisateur = 0
    utilisateur = request.user
    # Vérifier si l'utilisateur est authentifié
    if utilisateur.is_authenticated:
        # Récupérer l'ID de l'utilisateur
        gestion_liste_utilisateur.utilisateur.id = int(utilisateur.id)
        print(gestion_liste_utilisateur.utilisateur.id)
        gestion_liste_utilisateur.liste_utilisateur.id = gestion_liste_utilisateur.get_id_liste_utilisateur_en_cours()
        produits_liste_utilisateur = gestion_liste_utilisateur.get_1()
        id_liste_utilisateur = gestion_liste_utilisateur.liste_utilisateur.id

        context = {'produits_liste_utilisateur': produits_liste_utilisateur,'id_liste_utilisateur': id_liste_utilisateur}

        return render(request, 'ma_liste.html', context)

    else:
        return redirect('registration:login')

@user_passes_test(is_standard_user)
def remplir_liste_retour(request, id_liste_utilisateur,id_produit):
    gestion_liste_utilisateur = Gestion_liste_utilisateur()
    if request.method == 'POST':
        if id_produit:
            quantite_retour_key = f'quantity_{id_produit}'
            quantite_retour = request.POST.get(quantite_retour_key)
            if quantite_retour is not None:
                try:
                    gestion_liste_utilisateur.liste_utilisateur.id = id_liste_utilisateur
                    gestion_liste_utilisateur.produit.id = id_produit
                    gestion_liste_utilisateur.produit.quantite_retour = int(quantite_retour)

                    gestion_liste_utilisateur.update()

                    message = 'Quantité mise à jour avec succès'
                    return JsonResponse({"message": message}, status=200)


                except Exception as e:
                    return JsonResponse({"message":'Erreur lors de la mise à jour de la quantité'}, status=400)
            else:
                return JsonResponse({"message":'Aucune quantité spécifiée dans la requête'}, status=400)
        else:
            return JsonResponse({"message":'Aucun ID d\'association de stock-produit spécifié dans la requête'}, status=400)
    return JsonResponse({"message":'Méthode de requête invalide'}, status=405)

application_FFR/user_liste/templates/base_ma_liste.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Application logistique service medical FFR</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v6.1.1/js/all.js"></script>
    <script src="https://unpkg.com/htmx.org@^1.7.0/dist/htmx.min.js"></script>
</head>
<body>
<nav class="navbar is-link is-mobile" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <!-- Titre Accueil avec les mêmes styles que les autres éléments de la navbar -->
        <a class="navbar-item is-size-6 has-text-light" href="{% url 'user_liste:index_utilisateur' %}">
            Accueil
        </a>
        <!-- Burger avec dropdown -->
        <div class="navbar-burger has-text-light" aria-label="menu" aria-expanded="false" data-target="navbarDropdown">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div>
<div id="navbarDropdown" class="navbar-menu">
        <div class="navbar-end">
            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link has-text-light">
                    {{ user.first_name }}
                </a>
                <div class="navbar-dropdown is-right">
                    <a class="navbar-item" href="#">About</a>
                    <a class="navbar-item" href="#">Contact</a>
                    <hr class="navbar-divider">
                    <a class="navbar-item" href="{% url 'registration:logout' %}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Se déconnecter</a>
                    <form id="logout-form" action="{% url 'registration:logout' %}" method="post" style="display: none;">
                        {% csrf_token %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</nav>

<div id="content">
    {% block content %}{% endblock content %}
</div>
</body>
</html>

<script>
document.addEventListener('DOMContentLoaded', () => {
  // Get all "navbar-burger" elements
  const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

  // Add a click event on each of them
  $navbarBurgers.forEach( el => {
    el.addEventListener('click', () => {
      // Get the target from the "data-target" attribute
      const target = el.dataset.target;
      const $target = document.getElementById(target);

      // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
      el.classList.toggle('is-active');
      $target.classList.toggle('is-active');
    });
  });
});
</script>

application_FFR/user_liste/templates/index_utilisateur.html
{% extends 'base_ma_liste.html' %}
{% load crispy_forms_tags %}
{% block content %}

<section class="section">
    <div class="container">
        <h1 class="subtitle has-text-centered is-1 has-text-link">Logimed</h1>
        <hr>
        <div class="columns is-centered">
            <div class="column is-half has-text-centered">
                <a href="{% url 'user_liste:ma_liste' %}" class="button has-text-link is-focused is-large is-fullwidth mb-1">
                    <span class="icon">
                    <i class="fas fa-clipboard-list has-text-info"></i>
                    </span>
                    <span>Ma liste</span>
                </a>

            </div>
        </div>
    </div>
</section>

{% endblock content %}

application_FFR/user_liste/templates/ma_liste.html
{% extends 'base_ma_liste.html' %}
{% load crispy_forms_tags %}

{% block content %}

<section class="section has-background-light is-mobile">
<div class="box">
<h1 class="subtitle is-3 has-text-link has-text-centered mb-5 is-flex is-align-items-center is-justify-content-center">
    <span class="icon">
                    <i class="fas fa-clipboard-list has-text-info"></i>
                    </span>
                    <span class="ml-4">Ma liste</span></h1>
</div>


{% if produits_liste_utilisateur %}
<div class="box">
    <div class="table-container">
        <table class="table is-striped is-fullwidth">
            <thead>
                <tr>
                    <th>Produit</th>
                    <th>Depart</th>
                    <th>Retour</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for produit in produits_liste_utilisateur %}
                    <tr>
                        <td>{{ produit.nom_produit }}</td>
                        <td>{{ produit.quantite_depart }}</td>
                        <td>
                                <form hx-post="{% url 'user_liste:remplir_liste_retour' id_liste_utilisateur=id_liste_utilisateur id_produit=produit.id_produit %}" hx-target="#message_{{ produit.id_produit }}" hx-swap="outerHTML">                                {% csrf_token %}
                                <div class="field">
                                    <div class="control">
                                        <input type="number" id="quantity_{{ produit.id_produit }}" name="quantity_{{ produit.id_produit }}"
                                            value="{{ produit.quantite_retour }}" class="input is-small" min="0" max={{ produit.quantite_depart }}>
                                    </div>
                                </div>
                                </td>
                            <td>
                                <div class="field is-grouped">
                                    <div class="control">
                                                <button class="button is-primary is-focused is-small has-text-light" name="quantity_updated" type="submit">
                                                <span class="icon is-small">
                                                    <i class="fas fa-check"></i>
                                                </span></button>                                    </div>
                                </div>
                                </form>
                            </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

<div id="successNotification" class="notification is-small is-link" style= "display: none; position: fixed; bottom: 0px; right: 0px ;">
  Quantité mise à jour.
</div>
<div id="errorNotification" class="notification is-small is-danger" style="display: none; position: fixed; bottom: 0px; right: 0px;">
    Une erreur est survenue.
</div>


{% endif %}
<div class="box">
    <div class="field is-grouped is-justify-content-center">
    <div class="control">
    <a class="button is-link is-focused" href="{% url 'user_liste:index_utilisateur' %}">Valider</a>
    </div>
</div>
</div>

</section>


<script>
document.addEventListener("DOMContentLoaded", () => {
    // Get all forms with the 'hx-post' attribute
    let forms = document.querySelectorAll('[hx-post]');

    // Loop through each form and add submit event listener
    forms.forEach((form) => {
        form.addEventListener('submit', async (event) => {
            event.preventDefault();

            // Prepare the form data
            let formData = new FormData(form);

            // Send the form data asynchronously
            let response = await fetch(form.getAttribute('hx-post'), {
                method: 'POST',
                body: formData
            });

            // Parse the response as plain text
            let responseText = await response.text();

            // Check if the response was successful
            if (response.ok) {
                // Show success notification
                document.getElementById('successNotification').style.display = 'block';

                // Hide success notification after 3 seconds
                setTimeout(() => {
                    document.getElementById('successNotification').style.display = 'none';
                }, 2000);
            } else {
                // Display the error message
                let responseJson = await response.json();
                let errorNotification = document.getElementById('errorNotification');
                errorNotification.innerHTML = responseJson.message;
                errorNotification.style.display = 'block';
                setTimeout(() => {
                    errorNotification.style.display = 'none';
                }, 2000);
            }
        });
    });
});
</script>


{% endblock %}