application_FFR/admin_base/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'admin_base'

urlpatterns = [

    path('index/', views.index, name='index'),

]

application_FFR/admin_compte/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'admin_compte'

urlpatterns = [

    path('user_list/', views.user_list, name='user_list'),
    path('add_user/', views.AddUserView.as_view(), name='add_user'),
    path('delete_user/', views.delete_user, name='delete_user'),
    path('register/', views.RegisterView.as_view(), name='register'),  # Utilisation de votre vue d'inscription personnalisée

]

application_FFR/admin_liste/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'admin_liste'

urlpatterns = [

    path('depart/', views.depart, name='depart'),
    path('remplir_liste_depart/<int:id_liste_depart>/<int:id_produit>/', views.remplir_liste_depart, name='remplir_liste_depart'),
    path('create_liste_utilisateur/<int:id_liste_depart>/', views.create_liste_utilisateur, name='create_liste_utilisateur'),
    path('depart_retour/', views.depart_retour, name='depart_retour'),
    path('retour/', views.retour, name='retour'),
    path('verifier_liste_retour/<int:id_liste_utilisateur>/<int:id_produit>/', views.verifier_liste_retour, name='verifier_liste_retour'),
    path('valider_liste_retour/<int:id_liste_utilisateur>/', views.valider_liste_retour, name='valider_liste_retour'),
    path('liste_utilisateur_creee/', views.liste_utilisateur_creee, name='liste_utilisateur_creee'),
    path('mise_a_jour_stock/', views.mise_a_jour_stock, name='mise_a_jour_stock'),
    path('recherche_archive/', views.recherche_archive, name='recherche_archive'),
    path('display_archive/', views.display_archive, name='display_archive'),
]

application_FFR/admin_stock/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'admin_stock'

urlpatterns = [

    path('consommables/', views.stock_consommables, name='stock_consommables'),
    path('select_stock/', views.select_stock, name='select_stock'),
    path('display_produits/', views.display_produits, name='display_produits'),
    path('update_quantity/<int:id_produit>/', views.update_quantity, name='update_quantity'),
    path('produit_list/', views.produit_list, name='produit_list'),
    path('add_produit/', views.add_produit, name='add_produit'),
    path('delete_produit/', views.delete_produit, name='delete_produit'),

]

application_FFR/application_FFR/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView
from registration.views import CustomLoginView
from django.contrib.auth import views as auth_views
from registration.templates.registration import *

admin.site.site_header = 'Gestion des comptes'
admin.site.site_title = 'Gestion des comptes'
admin.site.index_title = ''


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', CustomLoginView.as_view(),name='login'),
    path('admin_base/', include('admin_base.urls')),
    path('admin_compte/', include('admin_compte.urls')),
    path('admin_liste/', include('admin_liste.urls')),
    path('admin_stock/', include('admin_stock.urls')),
    path('registration/', include('registration.urls')),
    path('user_liste/', include('user_liste.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

application_FFR/registration/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views
from . import views

app_name = 'registration'

urlpatterns = [

    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),  # Utilisation de votre vue d'inscription personnalisée
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

application_FFR/admin_base/views.py
from django.contrib.auth.decorators import user_passes_test
from .permissions import is_admin
from django.http import HttpResponse
from django.template import loader
import logging
logger = logging.getLogger("django")



# Page acceuil
@user_passes_test(is_admin)
def index(request):
    logger.debug("entrée dans la view 'Index'")
    template = loader.get_template('admin_base/index.html')
    context={}
    logger.warning('le contexte pour la view est vide')

    logger.debug("sortie dans la view 'Index', rendu du tempate...")

    return HttpResponse(template.render(context, request))

application_FFR/admin_base/templates/admin_base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Application logistique service medical FFR</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v6.1.1/js/all.js"></script>
    <script src="https://unpkg.com/htmx.org@^1.7.0/dist/htmx.min.js"></script>
</head>
<body>
<nav class="navbar is-link is-mobile" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <!-- Titre Accueil avec les mêmes styles que les autres éléments de la navbar -->
        <a class="navbar-item is-size-6 has-text-light" href="{% url 'admin_base:index' %}">
            Accueil
        </a>
        <!-- Burger avec dropdown -->
        <div class="navbar-burger has-text-light" aria-label="menu" aria-expanded="false" data-target="navbarDropdown">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div>
    <!-- Menu avec dropdown -->
    <div id="navbarMenu" class="navbar-menu">
        <div class="navbar-start">
            <a class="navbar-item has-text-light" href="{% url 'admin_compte:user_list' %}">Comptes</a>
            <a class="navbar-item has-text-light" href="{% url 'admin_stock:display_produits' %}">Stocks</a>
            <a class="navbar-item has-text-light" href="{% url 'admin_liste:depart_retour' %}">Listes</a>
        </div>
    </div>
 <div id="navbarDropdown" class="navbar-menu">
        <div class="navbar-end">
            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link has-text-light">
                    {{ user.first_name }}
                </a>
                <div class="navbar-dropdown is-right">
                    <a class="navbar-item" href="#">About</a>
                    <a class="navbar-item" href="#">Contact</a>
                    <hr class="navbar-divider">
                    <a class="navbar-item" href="{% url 'registration:logout' %}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Se déconnecter</a>
                    <form id="logout-form" action="{% url 'registration:logout' %}" method="post" style="display: none;">
                        {% csrf_token %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</nav>

<div id="content">
    {% block content %}{% endblock content %}
</div>
</body>
</html>
<script>
document.addEventListener('DOMContentLoaded', () => {
  // Get all "navbar-burger" elements
  const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

  // Add a click event on each of them
  $navbarBurgers.forEach( el => {
    el.addEventListener('click', () => {
      // Get the target from the "data-target" attribute
      const target = el.dataset.target;
      const $target = document.getElementById(target);

      // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
      el.classList.toggle('is-active');
      $target.classList.toggle('is-active');
    });
  });
});
</script>

application_FFR/admin_base/templates/admin_base/index.html
{% extends 'admin_base/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<section class="section">
    <div class="container">
        <h1 class="title has-text-centered is-1 has-text-link">Logimed</h1>
        <hr>
        <div class="columns is-centered">
            <div class="column is-half has-text-centered">
                <a href="{% url 'admin_compte:user_list' %}" class="button has-text-link is-focused is-large is-fullwidth mb-1">
                    <span class="icon has-text-warning">
                    <i class="fas fa-users"></i>
                    </span>
                    <span>Gestion Comptes</span>
                </a>

            </div>
        </div>
        <div class="columns is-centered">
            <div class="column is-half has-text-centered">
                <button class="button has-text-link is-focused is-large is-fullwidth mb-1" data-url="{% url 'admin_stock:display_produits' %}" onclick="window.location.href = this.getAttribute('data-url')">
                    <span class="icon has-text-primary">
                        <i class="fas fa-box"></i>
                    </span>
                    <span>Gestion Stocks</span>
                </button>
            </div>
        </div>
        <div class="columns is-centered">
            <div class="column is-half has-text-centered">
                <a href="{% url 'admin_liste:depart_retour' %}" class="button has-text-link is-focused is-large is-fullwidth mb-1">
                    <span class="icon has-text-info">
                        <i class="fas fa-clipboard-list"></i>
                    </span>
                    <span>Gestion Listes</span>
                </a>
            </div>
        </div>
    </div>
</section>

{% endblock content %}