application_FFR/admin_base/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'admin_base'

urlpatterns = [

    path('index/', views.index, name='index'),

]

application_FFR/admin_liste/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'admin_liste'

urlpatterns = [

    path('depart/', views.depart, name='depart'),
    path('remplir_liste_depart/<int:id_liste_depart>/<int:id_produit>/', views.remplir_liste_depart, name='remplir_liste_depart'),
    path('create_liste_utilisateur/<int:id_liste_depart>/', views.create_liste_utilisateur, name='create_liste_utilisateur'),
    path('depart_retour/', views.depart_retour, name='depart_retour'),
    path('retour/', views.retour, name='retour'),
    path('verifier_liste_retour/<int:id_liste_utilisateur>/<int:id_produit>/', views.verifier_liste_retour, name='verifier_liste_retour'),
    path('valider_liste_retour/<int:id_liste_utilisateur>/', views.valider_liste_retour, name='valider_liste_retour'),
    path('liste_utilisateur_creee/', views.liste_utilisateur_creee, name='liste_utilisateur_creee'),
    path('mise_a_jour_stock/', views.mise_a_jour_stock, name='mise_a_jour_stock'),
    path('recherche_archive/', views.recherche_archive, name='recherche_archive'),
    path('display_archive/', views.display_archive, name='display_archive'),
]

application_FFR/application_FFR/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView
from registration.views import CustomLoginView
from django.contrib.auth import views as auth_views
from registration.templates.registration import *

admin.site.site_header = 'Gestion des comptes'
admin.site.site_title = 'Gestion des comptes'
admin.site.index_title = ''


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', CustomLoginView.as_view(),name='login'),
    path('admin_base/', include('admin_base.urls')),
    path('admin_compte/', include('admin_compte.urls')),
    path('admin_liste/', include('admin_liste.urls')),
    path('admin_stock/', include('admin_stock.urls')),
    path('registration/', include('registration.urls')),
    path('user_liste/', include('user_liste.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

application_FFR/admin_liste/models.py
# Create your models here.
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from admin_stock.models import *
from django.contrib.auth.models import User



class AssociationListeDepartProduit(models.Model):
    id_association_liste_depart_produit = models.SmallAutoField(primary_key=True)
    id_liste_depart = models.ForeignKey('ListeDepart', models.DO_NOTHING, db_column='id_liste_depart', blank=True, null=True)
    id_produit = models.ForeignKey(Produit, models.DO_NOTHING, db_column='id_produit', blank=True, null=True)
    quantite_depart = models.SmallIntegerField(blank=True, null=True)
    quantite_retour = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'association_liste_depart_produit'
        unique_together = (('id_liste_depart', 'id_produit'),)


class AssociationListeUtilisateurProduit(models.Model):
    id_association_liste_utilisateur_produit = models.SmallAutoField(primary_key=True)
    id_liste_utilisateur = models.ForeignKey('ListeUtilisateur', models.DO_NOTHING, db_column='id_liste_utilisateur', blank=True, null=True)
    id_produit = models.ForeignKey(Produit, models.DO_NOTHING, db_column='id_produit', blank=True, null=True)
    quantite_depart = models.SmallIntegerField(blank=True, null=True)
    quantite_retour = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'association_liste_utilisateur_produit'
        unique_together = (('id_liste_utilisateur', 'id_produit'),)


class Deplacement(models.Model):
    id_deplacement = models.SmallAutoField(primary_key=True)
    nombre_joueurs = models.SmallIntegerField(blank=True, null=True)
    duree_deplacement = models.SmallIntegerField(blank=True, null=True)
    nombre_match = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'deplacement'
        unique_together = (('nombre_joueurs', 'duree_deplacement', 'nombre_match'),)


class Equipe(models.Model):
    id_equipe = models.SmallAutoField(primary_key=True)
    type_rugby = models.SmallIntegerField(blank=True, null=True)
    genre = models.CharField(max_length=10, blank=True, null=True)
    categorie_age = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'equipe'


class ListeDepart(models.Model):
    id_liste_depart = models.SmallAutoField(primary_key=True)
    id_deplacement = models.ForeignKey(Deplacement, models.DO_NOTHING, db_column='id_deplacement', blank=True, null=True)
    id_equipe = models.ForeignKey(Equipe, models.DO_NOTHING, db_column='id_equipe', blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'liste_depart'
        unique_together = (('id_deplacement', 'id_equipe'),)


class ListeUtilisateur(models.Model):
    id_liste_utilisateur = models.SmallAutoField(primary_key=True)
    id_utilisateur = models.ForeignKey(User, models.DO_NOTHING, db_column='id', blank=True, null=True)
    id_liste_depart = models.ForeignKey(ListeDepart, models.DO_NOTHING, db_column='id_liste_depart', blank=True, null=True)
    date_liste = models.DateField(blank=True, null=True)
    destination = models.CharField(max_length=30, blank=True, null=True)
    en_cours = models.BooleanField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'liste_utilisateur'
        unique_together = (('id_utilisateur', 'id_liste_depart', 'date_liste'),)

application_FFR/admin_liste/views.py
from django.contrib.auth.decorators import user_passes_test
from registration.permissions import is_admin, is_standard_user
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.http import JsonResponse
from django.template import loader
from .forms import *
import logging
from admin_stock.business.components.gestion_stock import Gestion_stock
from admin_liste.business.components.gestion_equipe import Gestion_equipe
from admin_liste.business.components.gestion_deplacement import Gestion_deplacement
from admin_liste.business.components.gestion_liste_depart import Gestion_liste_depart
from admin_liste.business.components.gestion_liste_utilisateur import Gestion_liste_utilisateur
logger = logging.getLogger("django")

#Gestion Liste

@user_passes_test(is_admin)
def depart_retour(request):

    template = loader.get_template('depart_retour.html')
    context = {}
    return HttpResponse(template.render(context, request))


# Preparer un depart

@user_passes_test(is_admin)
def depart(request):
    # Initialisation de vos classes métier
    gestion_equipe = Gestion_equipe()
    gestion_deplacement = Gestion_deplacement()
    gestion_liste_depart = Gestion_liste_depart()
    produits_stock = []
    produits_liste = []
    id_liste_depart = 0

    # Récupération de toutes les équipes en utilisant la méthode get_all() de votre classe métier
    equipes = gestion_equipe.get_all()

    # Si le formulaire est soumis (méthode POST)
    if request.method == 'POST':
        # Création d'une instance du formulaire avec les données soumises par l'utilisateur
        equipe_form = EquipeForm(request.POST)
        # Vérification si le formulaire est valide
        if equipe_form.is_valid():

            #1-choisir une équipe pour recuperer un id_equipe

            gestion_equipe.equipe.type_rugby = equipe_form.cleaned_data['type_rugby']
            gestion_equipe.equipe.genre = equipe_form.cleaned_data['genre']
            gestion_equipe.equipe.categorie_age = equipe_form.cleaned_data['categorie_age']

            gestion_liste_depart.equipe.id = gestion_equipe.get_id()
            print(gestion_liste_depart.equipe.id)

            # 2-creer un deplacement pour recuperer un id_deplacement si il existe déjà, reprendre l'id_existant.

            gestion_deplacement.deplacement.nombre_joueurs = equipe_form.cleaned_data['nombre_joueurs']
            gestion_deplacement.deplacement.duree_deplacement = equipe_form.cleaned_data['duree_deplacement']
            gestion_deplacement.deplacement.nombre_match = equipe_form.cleaned_data['nombre_match']

            gestion_deplacement.create()
            gestion_liste_depart.deplacement.id = gestion_deplacement.get_id()
            print(gestion_liste_depart.deplacement.id)

            # 3-verifier si la liste_depart n'existe pas déjà en testant la combinaison id_equipe,id_deplacement

            if gestion_liste_depart.get_id() is None:

                gestion_liste_depart.create()
                print("Liste creee")

            gestion_liste_depart.liste_depart.id = gestion_liste_depart.get_id()
            produits_liste = gestion_liste_depart.get_1()
            print(produits_liste)
            id_liste_depart = gestion_liste_depart.liste_depart.id

            produits_stock = gestion_liste_depart.get_liste_vierge()

            for produit_stock in produits_stock:
                for produit_liste in produits_liste:
                    if produit_stock['id_produit'] == produit_liste['id_produit']:
                        produit_stock['quantite_depart'] = produit_liste['quantite_depart']
                        produit_stock['quantite_retour'] = produit_liste['quantite_retour']
                        break


    else:
        # Création d'une instance du formulaire vide
        equipe_form = EquipeForm()

    utilisateur_choice_form = UtilisateurChoiceForm()

    context = {'equipes': equipes, 'equipe_form': equipe_form,'produits_stock': produits_stock, 'produits_liste': produits_liste, 'id_liste_depart': id_liste_depart, 'utilisateur_choice_form': utilisateur_choice_form}

    # Affichage de la page avec le formulaire
    return render(request, 'depart.html', context)

@user_passes_test(is_admin)
def remplir_liste_depart(request, id_liste_depart, id_produit):

    gestion_stock = Gestion_stock()
    gestion_liste_depart = Gestion_liste_depart()
    if request.method == 'POST':

        if id_produit:
            quantite_depart_key = f'quantity_{id_produit}'
            quantite_depart = request.POST.get(quantite_depart_key)

            if quantite_depart is not None:


                gestion_stock.produit.id = id_produit
                produit = gestion_stock.get_stock_1_produit()
                print(produit)

                if int(produit['quantite_stock']) >= int(quantite_depart):
                    try:
                        gestion_liste_depart.liste_depart.id = id_liste_depart
                        gestion_liste_depart.produit.id = id_produit
                        gestion_liste_depart.produit.quantite_depart = int(quantite_depart)


                        if gestion_liste_depart.test_association_produit_liste():

                            gestion_liste_depart.delete_association_liste_depart_produit()
                            gestion_liste_depart.update()
                            response_message = 'Quantité mise à jour avec succès'
                            return HttpResponse(response_message, status=200)

                        else:
                            gestion_liste_depart.create_association_liste_depart_produit()  # Utilise la méthode update_quantity de Gestion_stock
                            response_message = 'Quantité mise à jour avec succès'
                            return HttpResponse(response_message, status=200)



                    except Exception as e:
                        return JsonResponse({"message":'Erreur lors de la mise à jour de la quantité'}, status=400)

                else:
                    return JsonResponse({"message":'La quantite_depart est superieur à la quantite_stock'}, status=400)

            else:
                return JsonResponse({"message":'Aucune quantité spécifiée dans la requête'}, status=400)
        else:
            return JsonResponse({"message":'Aucun ID d\'association de stock-produit spécifié dans la requête'}, status=400)
    return JsonResponse({"message":'Méthode de requête invalide'}, status=405)

@user_passes_test(is_admin)
def create_liste_utilisateur(request, id_liste_depart):

    gestion_stock = Gestion_stock()
    gestion_liste_utilisateur = Gestion_liste_utilisateur()

    if request.method == 'POST':
        # Création d'une instance du formulaire avec les données soumises par l'utilisateur
        utilisateur_choice_form = UtilisateurChoiceForm(request.POST)

        # Vérification si le formulaire est valide
        if utilisateur_choice_form.is_valid():
            # Récupération des données du formulaire
            id_utilisateur = utilisateur_choice_form.cleaned_data['utilisateur']
            date_depart = utilisateur_choice_form.cleaned_data['date_depart']
            destination = utilisateur_choice_form.cleaned_data['destination']


            # Création de la liste utilisateur pour le depart avec les 4 paramètres

            try:
                gestion_liste_utilisateur.liste_depart.id = id_liste_depart
                print(gestion_liste_utilisateur.liste_depart.id)
                gestion_liste_utilisateur.utilisateur.id = int(id_utilisateur)
                print(gestion_liste_utilisateur.utilisateur.id)
                gestion_liste_utilisateur.liste_utilisateur.date = date_depart
                print(gestion_liste_utilisateur.liste_utilisateur.date)
                gestion_liste_utilisateur.liste_utilisateur.destination = destination
                print(gestion_liste_utilisateur.liste_utilisateur.destination)

                if gestion_liste_utilisateur.test_liste_en_cours():

                    print("Une liste est deja en cours pour cet utilisateur")
                    message = "Une liste est déjà en cours pour cet utilisateur"
                    return JsonResponse({"message": message}, status=405)


                elif not gestion_liste_utilisateur.create():
                    print("La liste utilisateur existe déjà")
                    message = "La liste utilisateur existe déjà"
                    return JsonResponse({"message": message}, status=400)

                else:

                    gestion_liste_utilisateur.create()
                    gestion_liste_utilisateur.liste_utilisateur.id = gestion_liste_utilisateur.get_id()
                    # Remplissage de la liste utilisateur
                    gestion_liste_utilisateur.create_association_liste_utilisateur_produit()
                    gestion_liste_utilisateur.get_1()

                    produits_liste_utilisateur=gestion_liste_utilisateur.get_1()

                    for produit in produits_liste_utilisateur:
                        gestion_stock.retirer_quantite_stock(produit['quantite_depart'], produit['id_produit'])

                    # Construire le message de réponse
                    message = 'La liste utilisateur a bien été créée.'
                    return JsonResponse({"message": message}, status=200)

            except Exception as e:
                return JsonResponse({"message": "Erreur lors de la création de la liste utilisateur."}, status=500)

        return JsonResponse({"message": "Méthode non autorisée."}, status=405)

    return JsonResponse({"message": "Méthode non autorisée."}, status=405)

@user_passes_test(is_admin)
def liste_utilisateur_creee(request):

    return render(request, 'liste_utilisateur_creee.html')


@user_passes_test(is_admin)
def retour(request):
    gestion_liste_utilisateur = Gestion_liste_utilisateur()
    produits_liste_utilisateur = []
    id_liste_utilisateur = 0

application_FFR/admin_liste/templates/create_liste_utilisateur.html
{% extends 'admin_base/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h1 class="title is-3 has-text-grey-dark has-text-centered mb-5">Créer une liste utilisateur</h1>

<div class="box">
    <h2 class="title is-4 has-text-grey-dark has-text-centered">Formulaire Utilisateur</h2>
    <form action="{% url 'admin_liste:create_liste_utilisateur' id_liste_depart=id_liste_depart %}" method="post">
        {% csrf_token %}
        {% crispy utilisateur_choice_form %}
        <button class="button is-primary" type="submit">Valider la liste utilisateur</button>
    </form>
</div>

{% endblock %}

application_FFR/admin_liste/templates/depart.html
{% extends 'admin_base/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<section class="section has-background-light is-mobile">
<div class="box">
<h1 class="subtitle is-3 has-text-link has-text-centered mb-5 is-flex is-align-items-center is-justify-content-center">
    <span class="icon is-large has-text-warning">
        <i class="fas fa-plane-departure"></i>
    </span>
    <span class="ml-3">Preparer un depart</span>
</h1>
</div>
<div class="box">
<h2 class="subtitle is-4 has-text-link mb-6">Construire un deplacement</h2>
<form action="{% url 'admin_liste:depart' %}" method="post" class="mb-5">
{% csrf_token %}
    <div class="container">
    {% crispy equipe_form %}
    <button class="button is-primary has-text-light" type="submit">Valider le deplacement</button>
    </div>
</form>
</div>

{% if produits_stock %}
<div class="box">
<h2 class="subtitle is-4 has-text-link mb-6">Construire la liste depart</h2>
    <h2 class="subtitle is-5 has-text-centered has-text-link mb-6">{{ selected_stock_nom }}</h2>
    <div class="table-container">
        <table class="table is-striped is-fullwidth">
            <thead>
                <tr>
                    <th>Produit</th>
                    <th>Stock</th>
                    <th>Depart</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for produit in produits_stock %}
                    <tr>
                        <td>{{ produit.nom_produit }}</td>
                        <td>{{ produit.quantite_stock }}</td>
                        <td>
                                <form hx-post="{% url 'admin_liste:remplir_liste_depart' id_liste_depart=id_liste_depart id_produit=produit.id_produit %}" hx-target="#message_{{ produit.id_produit }}" hx-swap="outerHTML">
                                {% csrf_token %}
                                <div class="field">
                                    <div class="control">
                                        <input type="number" id="quantity_{{ produit.id_produit }}" name="quantity_{{ produit.id_produit }}"
                                            value="{{ produit.quantite_depart }}" class="input is-small" min="0" max="{{ produit.quantite_stock }}">
                                    </div>
                                </div>
                                </td>
                            <td>
                                <div class="field is-grouped">
                                    <div class="control">
                                        <button class="button is-primary is-focused is-small has-text-light" name="quantity_updated" type="submit">
                                                <span class="icon is-small">
                                                    <i class="fas fa-check"></i>
                                                </span></button>                                    </div>
                                </div>
                                </form>
                            </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
   </div>
{% endif %}
<div id="successNotification" class="notification is-small is-link" style= "display: none; position: fixed; bottom: 0px; right: 0px ;">
  Quantité mise à jour.
</div>
<div id="errorNotification" class="notification is-small is-danger" style="display: none; position: fixed; bottom: 0px; right: 0px;">
    Une erreur est survenue.
</div>
{% if utilisateur_choice_form %}

<div class="box">
    <h2 class="subtitle is-4 has-text-link mb-6">Attribuer la liste à un utilisateur</h2>
    <form action="{% url 'admin_liste:create_liste_utilisateur' id_liste_depart=id_liste_depart %}" method="post">
        {% csrf_token %}
        <div class="container">
        {% crispy utilisateur_choice_form %}
        <button class="button is-focused is-primary has-text-light" type="submit">Valider la liste utilisateur (mise à jour du stock)</button>
        </div>
    </form>
<div id="message-container"></div>
</div>

{% endif %}

</section>

<script>
document.addEventListener("DOMContentLoaded", () => {
    // Get all forms with the 'hx-post' attribute
    let forms = document.querySelectorAll('[hx-post]');

    // Loop through each form and add submit event listener
    forms.forEach((form) => {
        form.addEventListener('submit', async (event) => {
            event.preventDefault();

            // Prepare the form data
            let formData = new FormData(form);

            // Send the form data asynchronously
            let response = await fetch(form.getAttribute('hx-post'), {
                method: 'POST',
                body: formData
            });

            // Parse the response as plain text
            let responseText = await response.text();

            // Check if the response was successful
            if (response.ok) {
                // Show success notification
                document.getElementById('successNotification').style.display = 'block';

                // Hide success notification after 3 seconds
                setTimeout(() => {
                    document.getElementById('successNotification').style.display = 'none';
                }, 2000);
            } else {
                // Display the error message
                // Parse the response as JSON
                let responseJson = await response.json();

                // Display the error message
                let errorNotification = document.getElementById('errorNotification');
                errorNotification.innerHTML = responseJson.message;
                errorNotification.style.display = 'block';

                // Hide error notification after 3 seconds
                setTimeout(() => {
                    errorNotification.style.display = 'none';
                }, 2000);
            }
        });
    });


    const utilisateurForm = document.querySelector('form[action="{% url 'admin_liste:create_liste_utilisateur' id_liste_depart=id_liste_depart %}"]');
    utilisateurForm.addEventListener('submit', async (event) => {
        event.preventDefault();

        // Vérification des quantités de départ par rapport aux quantités de stock
        const quantiteForms = document.querySelectorAll('[name^="quantity_"]');
        let isValid = true;
        quantiteForms.forEach((quantiteForm) => {
            const quantiteDepart = parseInt(quantiteForm.value);
            const quantiteStock = parseInt(quantiteForm.max);
            if (quantiteDepart > quantiteStock) {
                isValid = false;
                // Affichez un message d'erreur à l'utilisateur ou faites une autre action appropriée
                alert("La quantité de départ ne peut pas dépasser la quantité de stock.");
            }
        });

        // Si toutes les quantités de départ sont valides, soumettez le formulaire utilisateur_choice_form
        if (isValid) {
            let formData = new FormData(utilisateurForm);
            let response = await fetch(utilisateurForm.getAttribute('action'), {
                method: 'POST',
                body: formData
            });

            let data = await response.json();
            alert(data.message);
            if (response.ok) {
                // Optionnellement, vous pouvez rediriger ou effectuer d'autres actions en cas de succès
                window.location.href = '{% url "admin_base:index" %}';
            }
        }
    });

    {% if message %}
    alert("{{ message }}");
    {% endif %}
});







</script>

{% endblock %}

application_FFR/admin_liste/templates/retour.html
{% extends 'admin_base/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<section class="section has-background-light is-mobile">
<div class="box">
<h1 class="subtitle is-3 has-text-link has-text-centered mb-5 is-flex is-align-items-center is-justify-content-center"><span class="icon has-text-primary">
                        <i class="fas fa-plane-arrival"></i>
                    </span><span class="ml-4">Verifier un retour</span></h1>
</div>
<div class="box">
<h2 class="subtitle is-4 has-text-link mb-6">Recuperer la liste utilisateur en cours</h2>
<form action="{% url 'admin_liste:retour' %}" method="post" class="mb-5">
{% csrf_token %}
    <div class="container">
    {% crispy liste_utilisateur_form %}
    <button class="button is-primary has-text-light" type="submit">Choisir</button>
    </div>
</form>
</div>
{% if produits_liste_utilisateur %}
<div class="box">
<h2 class="subtitle is-4 has-text-link mb-6">Verifier la liste utilisateur</h2>
    <h2 class="subtitle is-4 has-text-centered has-text-link mb-6">{{ selected_stock_nom }}</h2>
    <div class="table-container">
        <table class="table is-striped is-fullwidth">
            <thead>
                <tr>
                    <th>Produit</th>
                    <th>Depart</th>
                    <th>Retour</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for produit in produits_liste_utilisateur %}
                    <tr>
                        <td>{{ produit.nom_produit }}</td>
                        <td>{{ produit.quantite_depart }}</td>
                        <td>
                                <form hx-post="{% url 'admin_liste:verifier_liste_retour' id_liste_utilisateur=id_liste_utilisateur id_produit=produit.id_produit %}" hx-target="#message_{{ produit.id_produit }}" hx-swap="outerHTML">
                                {% csrf_token %}
                                <div class="field">
                                    <div class="control">
                                        <input type="number" id="quantity_{{ produit.id_produit }}" name="quantity_{{ produit.id_produit }}"
                                            value="{{ produit.quantite_retour }}" class="input is-small" min="0" max="{{ produit.quantite_depart }}">
                                    </div>
                                </div>
                                </td>
                            <td>
                                <div class="field is-grouped">
                                    <div class="control">
                                                <button class="button is-primary is-focused is-small has-text-light" name="quantity_updated" type="submit">
                                                <span class="icon is-small">
                                                    <i class="fas fa-check"></i>
                                                </span></button>                                    </div>
                                </div>
                                </form>
                            </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

<div id="successNotification" class="notification is-small is-link" style= "display: none; position: fixed; bottom: 0px; right: 0px ;">
  Quantité mise à jour.
</div>
<div id="errorNotification" class="notification is-small is-danger" style="display: none; position: fixed; bottom: 0px; right: 0px;">
    Une erreur est survenue.
</div>

    <form id="validerListeRetourForm" action="{% url 'admin_liste:valider_liste_retour' id_liste_utilisateur=id_liste_utilisateur %}" method="post">
        {% csrf_token %}
        <div class="container">
        <button class="button is-primary has-text-light" type="submit">Valider la liste utilisateur (mise à jour du stock)</button>
        </div>
    </form>
{% endif %}
</div>
</div>
</section>


<script>
document.addEventListener("DOMContentLoaded", () => {
    // Get all forms with the 'hx-post' attribute
    let forms = document.querySelectorAll('[hx-post]');

    // Loop through each form and add submit event listener
    forms.forEach((form) => {
        form.addEventListener('submit', async (event) => {
            event.preventDefault();

            // Prepare the form data
            let formData = new FormData(form);

            // Send the form data asynchronously
            let response = await fetch(form.getAttribute('hx-post'), {
                method: 'POST',
                body: formData
            });

            // Parse the response as plain text
            let responseText = await response.text();

            // Check if the response was successful
            if (response.ok) {
                // Show success notification
                document.getElementById('successNotification').style.display = 'block';

                // Hide success notification after 3 seconds
                setTimeout(() => {
                    document.getElementById('successNotification').style.display = 'none';
                }, 2000);
            } else {
                // Display the error message
                let responseJson = await response.json();
                let errorNotification = document.getElementById('errorNotification');
                errorNotification.innerHTML = responseJson.message;
                errorNotification.style.display = 'block';
                setTimeout(() => {
                    errorNotification.style.display = 'none';
                }, 2000);
            }
        });
    });
    const validerListeRetourForm = document.getElementById('validerListeRetourForm');
    validerListeRetourForm.addEventListener('submit', async (event) => {
        event.preventDefault();

        let formData = new FormData(validerListeRetourForm);
        let response = await fetch(validerListeRetourForm.getAttribute('action'), {
            method: 'POST',
            body: formData
        });

        let data = await response.json();
        alert(data.message);
        if (response.ok) {
            window.location.href = '{% url "admin_base:index" %}';
        }
    });

    {% if message %}
    alert("{{ message }}");
    {% endif %}
});
</script>


{% endblock %}